name: swd
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dev: ^1.0.0
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_secure_storage: ^4.2.1
  flutter_svg: ^1.1.6
  fluttertoast: ^8.2.4
  freezed: ^2.2.0
  freezed_annotation: ^2.4.1
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  json_annotation: ^4.7.0
  logger: ^1.1.0
  shared_preferences: ^2.2.0
  stacked: ^3.2.7
  stacked_services: ^1.0.2
  http: ^0.13.5
  carousel_slider: ^4.1.1
  pinput: ^2.2.21
  form_builder_validators: ^7.7.1

dev_dependencies:
  build_runner: ^2.3.2
  json_serializable: ^6.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_gen_runner:
  hive_generator: ^2.0.0
  stacked_generator: ^1.3.3

flutter_gen:
  integrations:
    flutter_svg: true

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
